// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axkgjnsqmclhhrkkdqpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4a2dqbnNxbWNsaGhya2tkcXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDA2NDgsImV4cCI6MjA2ODMxNjY0OH0.MHZEkcPPhr5Dd8vmIWKK_ezdhNgSGcey8RpmvjceYlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});